spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/online_wallet
    username: postgres
    password: badiro12
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create  # Adjust as needed (update, create, create-drop, etc.)
    show-sql: false
    properties:
      hibernate:
        format_sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect  # Set the appropriate dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: <email>
    password: <password>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
logging:
  level:
    org:
      springframework:
        security: trace


